### ISSUE TITLE
supplement materials plz

### ISSUE THREAD

**Issue by YuGuilliman** [jixiaozhong/Sonic#5]
您好，我找不到本文章的supp.，能发个链接吗？
以及，我不大明白3.1、3.2所描述的两个part是怎么与Sonic关联的，我找不到他们的阶段产物与denoising UNet的联系，也没有说怎么注入
Any help will be greatful!

**Comment by jixiaozhong** [comment]
We apologize for not being able to present all details completely. We will add detailed descriptions of the network structure in the supplementary materials of the next version. The basic architecture of Sonic is consistent with Stable Video Diffusion, on top of which we have introduced the proposed motion controller and context-enhanced audio learning. The output of the motion controller is injected into each 2D/3D ResNet. Audio attention is divided into spatial audio attention and temporal audio attention, which are embedded after spatial cross attention and temporal cross attention, respectively.
