### ISSUE TITLE
GPU VRAM requirement

### ISSUE THREAD

**Issue by oisilener1982** [jixiaozhong/Sonic#7]
I know that this is not yet released but would it be possible to update us the vram requirement. Thanks in advance

**Comment by jixiaozhong** [comment]
We provide GPU memory information for your reference. During the inference phase, 32GB of GPU memory is sufficient. The GPU memory required for training is contingent upon the resolution and the length of the frames. Our default configuration approximately necessitates 70GB of GPU memory. Concurrently, if your GPU capacity is not large enough, you can employ methods such as gradient checkpointing or deepspeed zero stage 2 to reduce the GPU memory usage.

**Comment by nitinmukesh** [comment]
@oisilener1982 

So this is not for consumer GPU's. 
If this project is DiT based than we can't use quantization either.

**Comment by oisilener1982** [comment]
The output is really good. Echomimic is dead. THere is no other way but to buy rtx 5090 with 32gb of vram

**Comment by nitinmukesh** [comment]
@oisilener1982 
EchoMimic is not dead, they released v2 but for high VRAM only. I am still waiting for accelerated version.
I am thinking of workstation GPU, 48 GB set for atleast 2-3 years :)
https://www.nvidia.com/en-in/design-visualization/rtx-6000/

**Comment by oisilener1982** [comment]
NVIDIA RTX 6000 got more memory but rtx 5090 got more cuda cores (21,760 vs 18176). 
5090 also has higher Memory bandwidth 1.52 TB/s vs 960.0 GB/s
5090 also has higher Memory bus width at 512 vs 384

![Capture](https://github.com/user-attachments/assets/94cb2e67-f795-4ad9-8327-c22c4e4f203c)
