### ISSUE TITLE
THanks for the Demo. I just noticed the Eye problem sometimes

### ISSUE THREAD

**Issue by oisilener1982** [jixiaozhong/Sonic#8]
https://github.com/user-attachments/assets/546fc74b-c60d-424f-aebb-e3ffd6b47d57

**Comment by jixiaozhong** [comment]
Thank you for your attention to our work. Firstly, the probability of artifacts occurring in the eye region is relatively low. Such issues in certain cases may be attributed to the lower input resolution (512), which, after being compressed by the VAE, results in limited information in the eye region, thereby impeding model learning. Moreover, by choosing random seeds, increasing the resolution, or augmenting the number of inference steps, more optimal results can be effortlessly achieved.
