### ISSUE TITLE
Some questions about motino controller

### ISSUE THREAD

**Issue by chenerg** [jixiaozhong/Sonic#9]
1. 

>  the translation motion-bucket mt is computed
as the variance of bounding boxes of video clip, while the expression motion-bucket me is variance of relative landmarks. Both buckets are integers in the range of [0, 128].

So how do you determine  which number the mt or me is between 0 and 128 ?  I mean variance should be a computed value, which may be larger than 128.

2. 

> emb = W[Pe(mt),Pe(me)],

here the emb is emdding, but how the embedding is used in the diffusion block is not detailed.

**Comment by jixiaozhong** [comment]
Thanks. 
1. During the training process, video clips exceeding a value of 128 were excluded.
2. Within the ResnetBlock2D, the embedding is broadcasted and subsequently added to the input hidden states.
